sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      - script: ./bin/docker_build.sh 10/jdk/slim openjdk openjdk:10 openjdk:10-jdk openjdk:10-jdk-slim
      - script: ./bin/docker_build.sh 10/jre/slim openjdk:10-jre openjdk:10-jre-slim
      - script: ./bin/docker_build.sh 8/jre/alpine openjdk:8 openjdk:8-jre openjdk:8-jre-alpine

