sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script: ./bin/docker_build.sh openjdk/8/jre/alpine
    - stage: build
      script: ./bin/docker_build.sh openjdk/10/jdk/slim
    - stage: build
      script: ./bin/docker_build.sh openjdk/10/jre/slim

