sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      - script: ./bin/docker_build.sh 8/jre/alpine
      - script: ./bin/docker_build.sh 10/jdk/slim
      - script: ./bin/docker_build.sh 10/jre/slim

